### PR TITLE
Add textarea support for contain assertions

### LINKED ISSUE #59: Expected behavior for <textarea>?
Should you be able to use `.value()` to determine the value of a `<textarea>`?

```
expect( component.find( 'textarea' ) ).to.have.value( 'Hello world' );
```

### PR DESCRIPTION
**Pull request by ayrton**
Fixes #59

### CODE REVIEW

**Comment by vesln** [comment]
👍

**Comment by andreasklinger** [comment]
:+1:

**Comment by ljharb** [comment]
We may also want special support for "select" elements, whose "value" should really be the value of the option matching the selected index

**Comment by ayrton** [comment]
@ljharb good thinking! I'll create a different PR (hopefully next Friday)

**Comment by danielbachhuber** [comment]
💯

**Pull request merged**
