### PR TITLE
Fix to allow React 17

### PR DESCRIPTION
**Pull request by SailingSteve**
Initial checkin to support React 17

### CODE REVIEW

**Comment by ljharb** [comment]
React 17 support is blocked on there being an official react 17 enzyme adapter.

**Comment by perrin4869** [comment]
hm... recent `npm` versions fail to install without the `--legacy-peer-deps` flag or `--force` flag
I've been using `chai-enzyme` just fine with `v17` and the unofficial adapter by `wojtekmaj`...
Even without the official adapter, I think support for react 17 isn't realistically going to need changes in this module?

**Comment by ljharb** [comment]
@perrin4869 it needs this module to *test* on react 17.

**Comment by perrin4869** [comment]
Would it be acceptable to test using the unofficial module for now?

**Comment by ljharb** [comment]
No; if the unofficial adapter passed tests, there'd be an official adapter.

**Comment by perrin4869** [comment]
Well, in this case it would just need to be good enough to pass the tests in this repo though right?

**Pull request closed without merging**
