### PR TITLE
Add Typescript definition file

### PR DESCRIPTION
**Pull request by idoo**
Source https://github.com/asvetliakov/typings-chai-enzyme/blob/master/index.d.ts

### CODE REVIEW

**Comment by asvetliakov** [comment]
@idoo 
This is not correct TS definition file. This typings relies on old typings augmenting behavior and chai/enzyme definitions from typings registry. Furthermore, it will break anyone with new 2.0 TS types system.
I'd implement it via new ```@types``` from TS 2.0 (in next few days current ```@types``` should be updated to latest DT versions)

**Comment by ayrton** [comment]
Anyone else that can verify this works or does not work? We, @producthunt, do not use TS so can't verify.

**Comment by ljharb** [comment]
I wouldn't recommend adding a TS type definitions file unless CI also can enforce that it's correct - otherwise it will just drift out of date with every PR.

**Comment by andreasklinger** [comment]
closing - old PR - no activity - feel free to reopen

**Pull request closed without merging**
