### PR TITLE
Remove react-addons-test-utils peerDependency

### PR DESCRIPTION
**Pull request by remcohaszing**
It's not used by chai-enzyme. It's kept as a devDepenceny, because
some versions of enzyme use it.

### CODE REVIEW

**Comment by rongierlach** [comment]
would appreciate if we could merge this 👍

**Comment by ayrton** [comment]
I don't think we can. Just tried removing them and then the tests no longer succeed:

```
$ npm test

> chai-enzyme@0.7.0 test /Users/adc/Developer/producthunt/chai-enzyme
> npm run test:lint && npm run test:unit


> chai-enzyme@0.7.0 test:lint /Users/adc/Developer/producthunt/chai-enzyme
> standard --verbose | snazzy


> chai-enzyme@0.7.0 test:unit /Users/adc/Developer/producthunt/chai-enzyme
> cross-env NODE_ENV=test mocha test/**/*.test.js

react-dom@15.5+ and react-test-renderer are implicit dependencies when usingreact@15.5+ with enzyme. Please add the appropriate version to yourdevDependencies. See https://github.com/airbnb/enzyme#installation
/Users/adc/Developer/producthunt/chai-enzyme/node_modules/enzyme/build/react-compat.js:154
      throw e;
      ^

Error: Cannot find module 'react-addons-test-utils'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /Users/adc/Developer/producthunt/chai-enzyme/node_modules/enzyme/build/react-compat.js:143:21
    at Object.<anonymous> (/Users/adc/Developer/producthunt/chai-enzyme/node_modules/enzyme/build/react-compat.js:214:5)
```

**Comment by remcohaszing** [comment]
I think you removed it as a devDependency on your own machine. I kept it there, hence the tests still work. Travis seems to agree with me.

**Comment by ayrton** [comment]
@remcohaszing something must have borked up my development setup, you're right.

**Pull request merged**
